import Head from "next/head";
import Calculator from "../components/Calculator/Calculator";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Calculator</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className={styles.root}>
        <div className={styles.container}>
          <Calculator />
        </div>
      </main>
    </>
  );
}
